### PR TITLE
Create tests for list_all_notes

### PR DESCRIPTION
**Pull request by ebarnsli**
The other PR someone submitted wasn't actually tests for the function, they just added code. So where we make an actual unit test for list_all_notes. 

We mock githubs response when we call get_repo to return a list of mocked files... and then we test that the file names were printed to std.out. We also verify the parameters that github methods are called with

### CODE REVIEW

**Comment by LeonardoFurtado** [comment]
LGTM, thanks @ebarnsli

**Comment by LeonardoFurtado** [comment]
@ebarnsli  Travis is show me `AttributeError: 'TestUser' object has no attribute 'capsys'` for some reason. Can u help me with this?

**Comment by ebarnsli** [comment]
Yep it’s a pytest argument. I’ll get back to you with it soon

**Comment by ebarnsli** [comment]
pytest --capture=sys

Should add that to ur pytest command for Travis

**Comment by LeonardoFurtado** [comment]
> pytest --capture=sys
> 
> Should add that to ur pytest command for Travis

my .travis.yml have `coverage run --source=scripts setup.py test` command, where do I put this?

**Comment by LeonardoFurtado** [comment]
done ;)

**Comment by ebarnsli** [comment]
Oh you figured it out ?? Nice! Otherwise I can look later :)

**Comment by LeonardoFurtado** [comment]
> Oh you figured it out ?? Nice! Otherwise I can look later :)

I change `coverage` command to `python3 -m pytest --capture=sys --cov=scripts test/` using pytest-cov.

**Pull request merged**
